import React from "react";

/* EDIT TERMS AND CONDITIONS TO BE MORE INSIDIOUS */

const PrivacyText = () => {
    const url = "PLACEHOLDER_URL";
    return (
        <>
            <p className="text-modal">At Memit, currently accessible from https://gaming-life-lhw-1.herokuapp.com/, one of our main priorities is the privacy of the data provided by our visitors. This Privacy Policy document contains types of information that is collected and recorded by Memit and how we use it. If you have additional questions or require more information about our Privacy Policy, do not hesitate to contact us. This Privacy Policy applies only to our online activities and is valid for visitors to our website with regards to the information that they shared and/or collect in Memit. This policy is not applicable to any information collected offline or via channels other than this website.</p>
            <p className="text-modal">By using our website, you hereby consent to our Privacy Policy and agree to its terms. The personal information that you are asked to provide, and the reasons why you are asked to provide it, will be made known to you to a certain extent at the point we ask you to provide your personal information. If you contact us directly, we may receive additional information about you such as your name, email address, phone number, the contents of the message and/or attachments you may send us, and any other information you may choose to provide. When you register for an Account, we may ask for your contact information, including items such as name, company name, address, email address, and telephone number.</p>
            <p className="text-modal">We use the information we collect in various ways. This is in order to provide, operate, and maintain our website, as well as to continually improve, personalize, and expand our website. Using the information, we seek to understand and analyze how you use our website, and will use the information whenever necessary to develop new products, services, features, and functionality. We may use the information to communicate with you, either directly or through one of our partners, including for customer service, to provide you with updates and other information relating to the website, and for marketing and promotional purposes. We may also use the information to find and prevent frauds.</p>
            <p className="text-modal">Memit follows a standard procedure of using log files. These files log visitors when they visit websites. All hosting companies do this and a part of hosting services' analytics. The information collected by log files include internet protocol (IP) addresses, browser type, Internet Service Provider (ISP), date and time stamp, referring/exit pages, and possibly the number of clicks. These may be linked to any information that is personally identifiable. The purpose of the information is for analyzing trends, administering the site, tracking users' movement on the website, and gathering demographic information. By agreeing to these policies, you consent to the information collected to be used for the purposes of improving and enhancing our company and its products.</p>
            <p className="text-modal">Like any other website, Memit uses 'cookies'. These cookies are used to store information including visitors' preferences, and the pages on the website that the visitor accessed or visited. The information is used to optimize the users' experience by customizing our web page content based on visitors' browser type and/or other information.</p>
            <p className="text-modal">You may consult this list to find the Privacy Policy for each of the advertising partners of Memit. Third-party ad servers or ad networks uses technologies like cookies, JavaScript, or Web Beacons that are used in their respective advertisements and links that appear on Memit, which are sent directly to users' browser. They automatically receive your IP address when this occurs. These technologies are used to measure the effectiveness of their advertising campaigns and/or to personalize the advertising content that you see on websites that you visit. Memit may or may not have no access to or control over these cookies that are used by third-party advertisers.</p>
            <p className="text-modal">Memit's Privacy Policy does not apply to other advertisers or websites. Thus, we are advising you to consult the respective Privacy Policies of these third-party ad servers for more detailed information. It may include their practices and instructions about how to opt-out of certain options.  You can choose to disable cookies through your individual browser options. To know more detailed information about cookie management with specific web browsers, it can be found at the browsers' respective websites.</p>
            <p className="text-modal">Under the CCPA Privacy Rights, among other rights, California consumers have the right to request that a business that collects a consumer's personal data disclose the categories and specific pieces of personal data that a business has collected about consumers, request that a business delete any personal data about the consumer that a business has collected, or request that a business that sells a consumer's personal data, not sell the consumer's personal data. If you make a request, we may choose not to respond to you depending on the circumstances of your request. If you would like to exercise any of these rights, please contact us first. If you fail to contact us first in order to exercise any of these rights, you consent to forfeiting your ability to exercise any of these rights with Memit.</p>
            <p className="text-modal">We would like to make sure you are fully aware of all of your data protection rights. Every user is entitled to the following rights. You have the right to access and request copies of your personal data. We will charge you a small fee for this service. You have the right to rectification, meaning you have the right to request that we correct any information you believe is inaccurate. You also have the right to request that we complete the information you believe is incomplete. These rights may or may not be exercisable depending on the decisions made by Memit. You do not have the right to erasure, meaning the right to request that we erase your personal data, under any conditions, or the right to restrict processing, meaning the right to request that we restrict the processing of your personal data, under any conditions. You do not have the right to object to processing, meaning the right to object to our processing of your personal data, under any conditions. You have the right to data portability, meaning the right to request that we transfer the data that we have collected to another organization, or directly to you, under some conditions. If you make a request, we may or may not choose to respond to you. If you would like to exercise any of these rights, please contact us. If you fail to contact us first in order to exercise any of these rights, you consent to forfeiting your ability to exercise any of these rights with Memit.</p>
            <p className="text-modal">Another part of our priority is adding protection for children while using the internet. We encourage parents and guardians to observe, participate in, and/or monitor and guide their online activity. Memit may or may not knowingly collect any Personal Identifiable Information from children under the age of 13. If you think that your child provided this kind of information on our website, we strongly encourage you to contact us immediately and we will do our best efforts to deal with such information from our records.</p>
        </>
    );
};

export default PrivacyText;